# created by : Kuldeep Pandit
# date : 25-05-2024

name: common
description: this package includes base class.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  responsive_builder: ^0.7.0
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  pretty_dio_logger: ^1.1.1
  json_annotation: ^4.8.0
  shimmer:
  intl: ^0.19.0
  riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  flutter_hooks: ^0.20.5
  dartz: ^0.10.1
  internet_connection_checker_plus: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^4.0.0
  test: ^1.21.0
  build_runner: ^2.4.10
  riverpod_generator: ^3.0.0-dev.6
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0
  logging: ^1.2.0

